### ISSUE TITLE
解析这份日志记录时会错误

### ISSUE THREAD

**Issue by daviyang35** [ddcw/innodb_status#1]
运行时解析错误：
```
[root@manage innodb_status]# cat innodb_status.txt | python3 innodb_status.py
Traceback (most recent call last):
  File "innodb_status.py", line 56, in <module>
    format_str.set_all()
  File "/tmp/innodb_status/innodb_status_tool.py", line 426, in set_all
    self.set_dead_lock()
  File "/tmp/innodb_status/innodb_status_tool.py", line 177, in set_dead_lock
    s1_info = re.compile('\*\*\* \(1\) TRANSACTION:(.+)\*\*\* \(1\) WAITING FOR THIS LOCK TO',re.S).findall(deadlock)[0].strip()
IndexError: list index out of range
```

输入文件：
[innodb_status.txt](https://github.com/ddcw/innodb_status/files/9997889/innodb_status.txt)

**Comment by ddcw** [comment]
> 运行时解析错误：
> 
> ```
> [root@manage innodb_status]# cat innodb_status.txt | python3 innodb_status.py
> Traceback (most recent call last):
>   File "innodb_status.py", line 56, in <module>
>     format_str.set_all()
>   File "/tmp/innodb_status/innodb_status_tool.py", line 426, in set_all
>     self.set_dead_lock()
>   File "/tmp/innodb_status/innodb_status_tool.py", line 177, in set_dead_lock
>     s1_info = re.compile('\*\*\* \(1\) TRANSACTION:(.+)\*\*\* \(1\) WAITING FOR THIS LOCK TO',re.S).findall(deadlock)[0].strip()
> IndexError: list index out of range
> ```
> 
> 输入文件： [innodb_status.txt](https://github.com/ddcw/innodb_status/files/9997889/innodb_status.txt)

请提供下 数据库版本信息

**Comment by ddcw** [comment]
> 运行时解析错误：
> 
> ```
> [root@manage innodb_status]# cat innodb_status.txt | python3 innodb_status.py
> Traceback (most recent call last):
>   File "innodb_status.py", line 56, in <module>
>     format_str.set_all()
>   File "/tmp/innodb_status/innodb_status_tool.py", line 426, in set_all
>     self.set_dead_lock()
>   File "/tmp/innodb_status/innodb_status_tool.py", line 177, in set_dead_lock
>     s1_info = re.compile('\*\*\* \(1\) TRANSACTION:(.+)\*\*\* \(1\) WAITING FOR THIS LOCK TO',re.S).findall(deadlock)[0].strip()
> IndexError: list index out of range
> ```
> 
> 输入文件： [innodb_status.txt](https://github.com/ddcw/innodb_status/files/9997889/innodb_status.txt)

该问题已在 v0.3 版本修复, 请下载最新版本验证. 根据你提供的 innodb_status.txt 文件得到如下结果:
`说明:
采集时间: 2022-11-14 01:20:35
下面涉及到的 每秒平均值 计算时间均为最近 5 秒内

master线程:
系统繁忙程度(越大越繁忙): 99.46 %
日志写入和刷新次数: 1157107

SEMAPHORES信号量:
rw_s_spin_wait_count 0
rw_s_spin_round_count 73465098
rw_s_os_wait_count 7295351
rw_x_spin_wait_count 0
rw_x_spin_round_count 753425836
rw_x_os_wait_count 5984570
rw_sx_spin_wait_count 34693346
rw_sx_spin_round_count 473036574
rw_sx_os_wait_count 2930279
每次空转等待的锁: rw_s:73465098.00  rw_x:753425836.00 rw_sx:13.63

死锁(最近一条)
产生死锁的时间: 2022-11-13 
事务ID:650062072  锁类型:X  thread_id:10584809  10216314621 172.16.1.68 root updating SQL如下:
update order

         SET status = 5,
            
            
            
            
                mtime = '2022-11-13 23:35:09.903' 
        where id = 3000007

事务ID:650062073  锁类型:X  thread_id:10525657  10216314613 172.16.1.70 root Searching rows for update SQL如下:
UPDATE order SET mtime=from_unixtime(1668353709),status=5 WHERE status=0

回滚事务: 650062072

事务汇总信息
max_trx_id : 652935497
min_trx_id : 652932007
max_undo_id: 0
purge线程状态: running but idle
undo包含的事务数: 1422
事务ID:652935492  事务状态:ACTIVE 0 sec  锁:6  堆大小:1136  锁行数:4  事务中修改或插入的行数:5  MYSQL_PROCESS_ID:10582983
事务ID:652935490  事务状态:ACTIVE 0 sec starting index read  锁:LOCK WAIT 2  堆大小:1136  锁行数:1  事务中修改或插入的行数:  MYSQL_PROCESS_ID:11043239
事务ID:652935489  事务状态:ACTIVE 0 sec  锁:6  堆大小:1136  锁行数:4  事务中修改或插入的行数:5  MYSQL_PROCESS_ID:9177354
事务ID:652935486  事务状态:ACTIVE 0 sec starting index read  锁:LOCK WAIT 2  堆大小:1136  锁行数:1  事务中修改或插入的行数:  MYSQL_PROCESS_ID:11043225
事务ID:652935475  事务状态:ACTIVE 0 sec starting index read  锁:LOCK WAIT 2  堆大小:1136  锁行数:1  事务中修改或插入的行数:  MYSQL_PROCESS_ID:10770670
事务ID:652935473  事务状态:ACTIVE 0 sec starting index read  锁:LOCK WAIT 2  堆大小:1136  锁行数:1  事务中修改或插入的行数:  MYSQL_PROCESS_ID:11041039
事务ID:652935470  事务状态:ACTIVE 0 sec starting index read  锁:LOCK WAIT 6  堆大小:1136  锁行数:3  事务中修改或插入的行数:3  MYSQL_PROCESS_ID:11009320
事务ID:652935466  事务状态:ACTIVE 0 sec starting index read  锁:LOCK WAIT 2  堆大小:1136  锁行数:1  事务中修改或插入的行数:  MYSQL_PROCESS_ID:11041402
事务ID:652935461  事务状态:ACTIVE 0 sec starting index read  锁:LOCK WAIT 2  堆大小:1136  锁行数:1  事务中修改或插入的行数:  MYSQL_PROCESS_ID:9924447
事务ID:652935449  事务状态:ACTIVE 0 sec starting index read  锁:LOCK WAIT 2  堆大小:1136  锁行数:1  事务中修改或插入的行数:  MYSQL_PROCESS_ID:10755138
事务ID:652935445  事务状态:ACTIVE 0 sec starting index read  锁:LOCK WAIT 3  堆大小:1136  锁行数:2  事务中修改或插入的行数:  MYSQL_PROCESS_ID:11041589
事务ID:652935444  事务状态:ACTIVE 0 sec starting index read  锁:LOCK WAIT 5  堆大小:1136  锁行数:3  事务中修改或插入的行数:3  MYSQL_PROCESS_ID:11010972
事务ID:652935230  事务状态:ACTIVE 1 sec starting index read  锁:21  堆大小:3520  锁行数:380  事务中修改或插入的行数:106  MYSQL_PROCESS_ID:10981413

文件IO
Pending normal 异步IO READ (对应read thread) :  [0, 0, 0, 0]
Pending normal 异步IO WRITE(对应write thread):  [0, 0, 0, 0]
挂起(pending)的redo log flush: 0
挂起(pending)的tablespace flush: 8648
OS总读次数: 355957495  速度: 3228.75 次/秒.  平均每次读 16384 字节
OS总写次数: 304569594  速度: 201.76 次/秒. 
OS总flush次数: 283221904  速度: 196.56 次/秒. 

insert/change buffer和自适应hash索引
已合并页的数量: 1 页.   ibuf空闲列表长度: 527 页.  ibuf大小: 529 页.  合并插入次数: 2735354
合并操作次数: insert buffer: 18324669  delete buffer: 6173751   purge buffer: 28665
无需合并操作的次数: insert buffer: 0  delete buffer: 0   purge buffer: 0
使用hash索引的查询 0.00次/秒  未使用hash使用的查询 29929.01次/秒   自适应hash索引使用率0.0%

日志信息(redo)
最新产生的LSN: 676370981639
已刷盘的LSN: 676370943043
最老的LSN: 675997740894
最新检查点LSN: 675997705120
redo已完成的IO次数: 266410465  速度:144.50次/秒

BUFFER POOL AND MEMORY(不含具体实例的,只含汇总的)
buffer pool 实例数(对应参数:innodb_buffer_pool_instances):  8
总内存: 8589934592 字节  (8.0 GB)
系统(字典)使用: 17873081 字节
buffer pool: 512256 页
free buffer: 6840 页
LRU        : 505416 页
old LRU    : 186725 页
脏页(flush list)            : 18579 页
等待读入的页(pending read)  : 1 页
等待的写(pending write) : LRU: 0 页.   flush_list(等待刷新的脏页): 0 页.   单页: 0 页
LRU made young(LRU中移动到前部的页数,就是经常使用的页) 64880467 页(速度:0.00/s),   non-young 1572909979 页(速度:0.00/s)
从磁盘读取的页: 355924166(0.00/s)   在内存中创建的页(无数据): 12604627(0.00/s)     写入磁盘的页: 32082820(0.00/s)
缓存命中率:972 / 1000
预读速度: 0.00/s   (因未被访问)驱除速度: 0.00/s   随机预读速度: 0.00/s

行操作ROW OPERATIONS
read view:  14
主进程ID: 6676 (sleeping)
插入行数: 832656754(700.46/s)   更新行数: 603226979(719.46/s)   删除行数: 27523493(0.00/s)   读行数: 403004294864(13149.57/s)
`
